name: ASP.NET Framework CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v2

    - uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore DocumentManager.API/DocumentManager.API.csproj

    - name: Build Project
      run: msbuild DocumentManager.API/DocumentManager.API.csproj /p:Configuration=Release
